version: '2'
services:
  planner:
    container_name: planner-container
    image: planner-image
    build:
      context: .
    volumes:
      - ./:/log
      - ./:/var/app
    env_file: ./variables.env
    environment:
      - NODE_ENV=development
    ports:
      - "9122:9122"






